<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE product [
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT shortDescription (#PCDATA)>
    <!ELEMENT longDescription (#PCDATA)>
    <!ELEMENT small (#PCDATA)>
    <!ELEMENT medium (#PCDATA)>
    <!ELEMENT large (#PCDATA)>
    <!ELEMENT original (#PCDATA)>
    <!ELEMENT imageURL (small, medium, large, original)>
    <!ELEMENT subCategory (#PCDATA)>
    <!ELEMENT availableSize (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT product (name, shortDescription, longDescription, imageURL, subCategory, availableSize, price)>
    <!ATTLIST name xml:lang NMTOKEN #IMPLIED>
    <!ATTLIST shortDescription xml:lang NMTOKEN #IMPLIED>
    <!ATTLIST longDescription xml:lang NMTOKEN #IMPLIED>
]>
<products>
<!-- TopCategory World_of_Nature  -->
<!-- SubCategory Animals  -->
<product>
<name xml:lang="x-default">Grizzly Bear</name>
<name xml:lang="de-DE">Grizzlybär</name>
<shortDescription xml:lang="x-default">Bear looking tired</shortDescription>
<shortDescription xml:lang="de-DE">Ein müder Bär lehnt sich auf einen Stein</shortDescription>
<longDescription xml:lang="x-default">Grizzly bears are severe predators and shouldn’t be underestimated only because of their harmless and cute looks like this picture displays them. If you happen to encounter a bear in the wild u should always try to get a way from it as fast as possible.</longDescription>
<longDescription xml:lang="de-DE">Grizzlybären sind äußerst gefährlich, auch wenn sie träge und kuschelig aussehen. Einem wilden Bären wie diesem sollte man sich in freier Wildbahn auf keinen Fall leichtfertig näheren sondern möglicht weit entfernt bleiben.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/grizzly-bear/grizzly-bear-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/grizzly-bear/grizzly-bear-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/grizzly-bear/grizzly-bear-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/grizzly-bear/grizzly-bear-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.00;25.50;32.95</price>
</product>
<product>
<name xml:lang="x-default">Great Grey Owl</name>
<name xml:lang="de-DE">Bartkauz</name>
<shortDescription xml:lang="x-default">A large grey owl in the woods</shortDescription>
<shortDescription xml:lang="de-DE">Eine große Eule im Wald</shortDescription>
<longDescription xml:lang="x-default">A very mysterious animal that stands for wisdom an intelligence is North America's largest owl, the great gray owl. This picture is going to fill your room with elegance and class.</longDescription>
<longDescription xml:lang="de-DE">Der Bartkauz ist die größte Eulenart Nordamerikas. Eulen gelten als Symbole für Weisheit und Intelligenz. Dieses Bild wird ihr Zimmer mit Eleganz und Klasse füllen.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/great-grey-owl/great-grey-owl-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/great-grey-owl/great-grey-owl-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/great-grey-owl/great-grey-owl-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/great-grey-owl/great-grey-owl-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>32x24;48x36;64x48</availableSize>
<price>12.85;17.99;23.89</price>
</product>
<product>
<name xml:lang="x-default">Swedish Moose</name>
<name xml:lang="de-DE">Schwedischer Elch</name>
<shortDescription xml:lang="x-default">A mooze with antlers</shortDescription>
<shortDescription xml:lang="de-DE">Ein Elchbulle mit mittelgroßem Geweih</shortDescription>
<longDescription xml:lang="x-default">A moose is symbolizing determination and endurance, so this poster might be something for your personality. Also do not mistake a moose and an elk are the same animal, only the people in the different locations vary with naming the animal.</longDescription>
<longDescription xml:lang="de-DE">Ein Elch in freier Wildbahn in einem Wald Schwedens. Das Poster zeigt gut die Tarnung des Tieres vor dunklerem Hintergrund durch den Teil des Waldbodens der sich etwa bis zur Hälfte des Bildes erstreckt. Ein Klassiker für alle Liebhaber borealer Waldgebiete.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/swedish-moose/swedish-moose-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/swedish-moose/swedish-moose-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/swedish-moose/swedish-moose-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/swedish-moose/swedish-moose-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>9.30;15.00;19.99</price>
</product>
<product>
<name xml:lang="x-default">European Hornet</name>
<name xml:lang="de-DE">Europäische Hornisse</name>
<shortDescription xml:lang="x-default">Close up shot of a hornet</shortDescription>
<shortDescription xml:lang="de-DE">Nahaufnahme einer Hornisse</shortDescription>
<longDescription xml:lang="x-default">Hornets are very scary looking insects, but their gorgeous color pattern can be a nice eye-catcher for your home. This hornet right here won't hurt if you aren't threatening her because the European hornet primarily feeds on crickets and grasshoppers.</longDescription>
<longDescription xml:lang="de-DE">Die Hornisse ist in Deutschland eine geschützte Art. Sie ist friedlich solange man sie nicht verletzt oder eine Gefahr für das Nest darstellt und versucht normalerweise zu fliehen statt zu stechen. Hornissen fressen hauptsächlich Insekten und verschmähen menschliche Speisen, daher tauchen sie am Kaffeetisch eigentlich nur auf um lästige Insekten wie Wespen oder Fliegen zu jagen.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/european-hornet/european-hornet-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/european-hornet/european-hornet-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/european-hornet/european-hornet-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/european-hornet/european-hornet-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>10.50;15.64;20.22</price>
</product>
<product>
<name xml:lang="x-default">Roman Snail</name>
<name xml:lang="de-DE">Weinbergschnecke</name>
<shortDescription xml:lang="x-default">Close up of a snail sticking on the side of a tree</shortDescription>
<shortDescription xml:lang="de-DE">Nahaufnahme einer Schnecke an der Seite eines Baumes</shortDescription>
<longDescription xml:lang="x-default">Perhaps you prefer a more leisurely pace in life, and this snail picture can embody that sentiment, adding a personal touch to your room. Roman snails, are also the largest land snails in north-West Europe, so u can also impress with some knowledge regarding this piece of art.</longDescription>
<longDescription xml:lang="de-DE">Die am weitesten verbreitete Schneckenart Europas. Weinbergschnecken sind Pflanzenfresser. In Deutschland, Österreich und der Schweiz stehen sie in der Natur unter Schutz. Zudem inzwischen auch durch eine EU-Richtlinie. Trotzdem gelten sie, besonders in Frankreich, als Delikatessen und werden dafür gezielt gezüchtet.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/roman-snail/roman-snail-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/roman-snail/roman-snail-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/roman-snail/roman-snail-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/roman-snail/roman-snail-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>23.00;30.45;38.00</price>
</product>
<product>
<name xml:lang="x-default">Blue Morpho Butterfly</name>
<name xml:lang="de-DE">Blauer Morphofalter</name>
<shortDescription xml:lang="x-default">A beautiful blue and black butterfly on a leaf</shortDescription>
<shortDescription xml:lang="de-DE">Ein hübscher, blau-schwarzer Schmetterling auf einem Blatt</shortDescription>
<longDescription xml:lang="x-default">Butterflies are the perfect insects to get some colorful spring vibes into your house. The blue morpho butterfly is also ranking among the world's largest butterflies and is known for its numerous eye spots that camouflage it during flight.</longDescription>
<longDescription xml:lang="de-DE">Der blaue Morphofalter, auch Himmelsfalter genannt ist ein großer Schmetterling der wegen seines hübschen Aussehens sehr beliebt ist. Die Unterseite der Flügel ist braun und weiß mit Flecken. Die blaue Farbe der Oberseite entsteht durch Interferenz des Lichts und nicht durch blaue Pigmente.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/blue-morpho-butterfly/blue-morpho-butterfly-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/blue-morpho-butterfly/blue-morpho-butterfly-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/blue-morpho-butterfly/blue-morpho-butterfly-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/blue-morpho-butterfly/blue-morpho-butterfly-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.99;23.99;29.99</price>
</product>
<product>
<name xml:lang="x-default">Red Birdwing</name>
<name xml:lang="de-DE">Schmetterling auf blauer Blüte</name>
<shortDescription xml:lang="x-default">Looking up at a butterfly sitting on a blossom</shortDescription>
<shortDescription xml:lang="de-DE">Blick von unten auf einen Schmetterling auf einer Blüte</shortDescription>
<longDescription xml:lang="x-default">A beautiful picture of a butterfly that will fit excellent with brown/orange, and red furniture because of its wing color. If you desire to observe the Red Birdwing in its natural habitat, it is primarily found in the Solomon Islands and is commonly observed obtaining nectar from flowers during the summer months.</longDescription>
<longDescription xml:lang="de-DE">Der Kontrast zwischen der dunklen Unterseite der Flügel des Schmetterlings und der blauen Blüte zieht den Blick auf das Bild. Es macht sich gut zu dunklerer Einrichtung die farblich zu dem Schmetterling passt.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/red-birdwing/red-birdwing-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/red-birdwing/red-birdwing-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/red-birdwing/red-birdwing-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/red-birdwing/red-birdwing-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>8.75;15.75;22;45</price>
</product>
<product>
<name xml:lang="x-default">Bird</name>
<name xml:lang="de-DE">Amsel</name>
<shortDescription xml:lang="x-default">A small black bird sitting on a gutter</shortDescription>
<shortDescription xml:lang="de-DE">Eine kleine Amsel auf einer Regenrinne</shortDescription>
<longDescription xml:lang="x-default">This poster looks somehow plain and quiet with the darker toned colors, but thats the beauty of this image. Worth to know: Black birds are known for their beautiful singing, the male black bird's song is one of the most complex of all British birds.</longDescription>
<longDescription xml:lang="de-DE">Das Poster erweckt einen herbstlichen Eindrück von Kühle und Stille. Die Amsel oder auch Schwarzdrossel ist für den wohlklingenden Reviergesang der Männchen weit bekannt.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/bird/bird-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/bird/bird-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/bird/bird-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/bird/bird-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>12.87;19.99;25.99</price>
</product>
<product>
<name xml:lang="x-default">Red Domestic Cat</name>
<name xml:lang="de-DE">Hauskatze mit beige-braunem Fell</name>
<shortDescription xml:lang="x-default">A red colored cat looking straight at you.</shortDescription>
<shortDescription xml:lang="de-DE">Eine beige und braun getigerte Hauskatze, die den Betrachter beobachtet</shortDescription>
<longDescription xml:lang="x-default">This poster is a great addition to your room if you like cute cats with red fur. It is worth knowing that the red coloring in domestic cats arises from ongoing, random genetic mixes among red domestic cats of diverse backgrounds.</longDescription>
<longDescription xml:lang="de-DE">Ein Muss für Katzenliebhaber! Diese Katze schaut den Betrachter nachdenklich an. Ob sie einen Streich ausheckt? Oder vielleicht versucht sie zu entscheiden welche Maus sie heute anschleppt?</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/red-domestic-cat/red-domestic-cat-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/red-domestic-cat/red-domestic-cat-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/red-domestic-cat/red-domestic-cat-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/red-domestic-cat/red-domestic-cat-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.99;26.98;34.89</price>
</product>
<product>
<name xml:lang="x-default">Brown Domestic Cat</name>
<name xml:lang="de-DE">Hauskatze mit braun-schwarzem Fell</name>
<shortDescription xml:lang="x-default">A brownish cat looking like its about to jump at you.</shortDescription>
<shortDescription xml:lang="de-DE">Diese Katze sieht aus als setze sie zum Sprung an</shortDescription>
<longDescription xml:lang="x-default">Cats are very curious animals and this particular one seems to absorb you with its cute button like eyes. If you own a cat, you might want to purchase this poster to observe your cat's response to the image.</longDescription>
<longDescription xml:lang="de-DE">Katzen sind niedlich und neugierig und haben einen starken Jagd- und Spielstrieb. Dieses Poster bringt Dynamik und gute Laune in jedes Zimmer. Katzenhalter können dieses Poster auch für ihre Katze aufhängen und deren Reaktion darauf beobachten.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/animals/brown-domestic-cat/brown-domestic-cat-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/animals/brown-domestic-cat/brown-domestic-cat-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/animals/brown-domestic-cat/brown-domestic-cat-large.webp</large>
<original>/assets/img/products/flora_and_fauna/animals/brown-domestic-cat/brown-domestic-cat-original.webp</original>
</imageURL>
<subCategory>Animals</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.90;25.29;30.00</price>
</product>
<!-- SubCategory Flowers  -->
<product>
<name>Pink Dahlia</name>
<shortDescription>The pink dhalia blossom close up. </shortDescription>
<longDescription>Ideal for those seeking to brighten their room with vibrant hues, this pink blossom, known as the pink Dahlia, can be crafted in designs ranging from uncomplicated stars to intricate balls and waterlily-like blooms.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/pink-dahlia/pink-dahlia-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/pink-dahlia/pink-dahlia-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/pink-dahlia/pink-dahlia-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/pink-dahlia/pink-dahlia-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>0.30;1.45;5.99</price>
</product>
<product>
<name>Cactus Dahlia Pink White</name>
<shortDescription>A pink and white dahlia blossom close up.</shortDescription>
<longDescription>If you like a more mixed color pattern like this pink and white Dahlia u should consider this beautiful picture. A fact to know: Dahlias have no scent, making them an ideal bloom for people with allergies.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-pink-white/cactus-dahlia-pink-white-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-pink-white/cactus-dahlia-pink-white-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-pink-white/cactus-dahlia-pink-white-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-pink-white/cactus-dahlia-pink-white-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>0.99;4.00;7.99</price>
</product>
<product>
<name>Cactus Dahlia, Yellow/Pink</name>
<shortDescription>A dahlia in a rare yellow and pink colorway</shortDescription>
<longDescription>Another Dahlia color pattern that as a more exotic look. The bold red and yellow petals are perfectly offset by the center of the flower, and the image is going to add a touch of elegance to any room.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-yellow-pink/cactus-dahlia-yellow-pink-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-yellow-pink/cactus-dahlia-yellow-pink-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-yellow-pink/cactus-dahlia-yellow-pink-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/cactus-dahlia-yellow-pink/cactus-dahlia-yellow-pink-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.10;24.90;29.99</price>
</product>
<product>
<name>Jerusalem Artichoke</name>
<shortDescription>The blossom of an artichoke.</shortDescription>
<longDescription>A very elegant flower that fits in every room. This poster also serves as an excellent conversation starter, because hearing about the fact that this is an artichoke blossom will surely catch people off guard, when they discover it belongs to an artichoke. </longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/jerusalem-artichoke/jerusalem-artichoke-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/jerusalem-artichoke/jerusalem-artichoke-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/jerusalem-artichoke/jerusalem-artichoke-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/jerusalem-artichoke/jerusalem-artichoke-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>23.59;31.75;38.00</price>
</product>
<product>
<name>Snowdrop Anemone</name>
<shortDescription>A blossom in all its details.</shortDescription>
<longDescription>Whether you have a passion for flowers or just enjoy captivating photography, this poster featuring a graceful white Snowdrop Anemone is sure to satisfy your aesthetic cravings. These flowers, known for their rarity, garner even more popularity as they exclusively bloom in the spring.</longDescription>
<price>12.38;25.99;49.90</price>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/snowdrop-anemone/snowdrop-anemone-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/snowdrop-anemone/snowdrop-anemone-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/snowdrop-anemone/snowdrop-anemone-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/snowdrop-anemone/snowdrop-anemone-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
</product>
<product>
<name>Violas</name>
<shortDescription>A flower meadow in purple and yellow.</shortDescription>
<longDescription>Looking at this field of flowers and their nicely arranged colors can be very comforting for you and the persons living with you. Having this picture in your house is going to help with bad moods and stress.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/violas/violas-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/violas/violas-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/violas/violas-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/violas/violas-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>35.70;50.00;65.89</price>
</product>
<product>
<name>Yellow and Orange Tulips</name>
<shortDescription>Orange Tulips on a field shot at close.</shortDescription>
<longDescription>"Let the spring into your home and brighten up your rooms! The beautiful yellow/orange combo will especially go well with green, brown and light yellow tones."</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/yellow-and-orange-tulips/yellow-and-orange-tulips-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/yellow-and-orange-tulips/yellow-and-orange-tulips-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/yellow-and-orange-tulips/yellow-and-orange-tulips-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/yellow-and-orange-tulips/yellow-and-orange-tulips-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>18.50;25.30;31.90</price>
</product>
<product>
<name>Mixed-Colored Tulips</name>
<shortDescription>Red, orange and pink tulips next to each other. </shortDescription>
<longDescription>This is another tulip picture for people that like a little more color in their room. A nice way to combine with a white wall or furniture to add a bit of accents at your place.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/mixed-colored-tulips/mixed-colored-tulips-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/mixed-colored-tulips/mixed-colored-tulips-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/mixed-colored-tulips/mixed-colored-tulips-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/mixed-colored-tulips/mixed-colored-tulips-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.99;24.99;38.10</price>
</product>
<product>
<name>Garden Roses</name>
<shortDescription>Roses with tinge of white in a garden.</shortDescription>
<longDescription>Roses are on of the symbols for love and romance, so this picture would be a perfect gift for a loved one on Valentine's Day, an anniversary, or another special occasion. </longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/garden-roses/garden-roses-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/garden-roses/garden-roses-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/garden-roses/garden-roses-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/garden-roses/garden-roses-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.99;24.99;38.10</price>
</product>
<product>
<name>Anthurium</name>
<shortDescription>Red Anthurium shot from above.</shortDescription>
<longDescription>A flower that is very rare due to its appearance in tropical climates, makes this close up to a more unique piece. The eye catching red color is going to attract all looks to your new poster.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/flowers/anthurium/anthurium-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/flowers/anthurium/anthurium-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/flowers/anthurium/anthurium-large.webp</large>
<original>/assets/img/products/flora_and_fauna/flowers/anthurium/anthurium-original.webp</original>
</imageURL>
<subCategory>Flowers</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>16.30;24.80;30.00</price>
</product>
<!-- SubCategory Trees  -->
<product>
<name>Indian Summer Red Beeches </name>
<shortDescription>An orange/red beech on the side of a small bridge.</shortDescription>
<longDescription>A not so special looking picture, but for some persons this won't matter. Good to know: The beech is capable of reaching heights up to 50 meters and has a typical lifespan of 150 to 200 years.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/trees/indian-summer-red-beeches/indian-summer-red-beeches-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/trees/indian-summer-red-beeches/indian-summer-red-beeches-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/trees/indian-summer-red-beeches/indian-summer-red-beeches-large.webp</large>
<original>/assets/img/products/flora_and_fauna/trees/indian-summer-red-beeches/indian-summer-red-beeches-original.webp</original>
</imageURL>
<subCategory>Trees</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>12.89;19.99;29.99</price>
</product>
<product>
<name>Indian summer orange Tree</name>
<shortDescription>A beech next to a rail crossing sign.</shortDescription>
<longDescription>A motive that creates wanderlust while warm colors and small details weave a story of nature's change. Adding this poster to your space brings u a nice touch of nature.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-tree/indian-summer-orange-tree-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-tree/indian-summer-orange-tree-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-tree/indian-summer-orange-tree-large.webp</large>
<original>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-tree/indian-summer-orange-tree-original.webp</original>
</imageURL>
<subCategory>Trees</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>15.78;21.90;27.97</price>
</product>
<product>
<name>Indian Summer Orange Beech</name>
<shortDescription>The crown of an orange beech. </shortDescription>
<longDescription>This warm colored tree motive will create a relaxed atmosphere in your home. It is going to be a good wall poster in a living room with a nice and comfortable couch. </longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-beech/indian-summer-orange-beech-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-beech/indian-summer-orange-beech-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-beech/indian-summer-orange-beech-large.webp</large>
<original>/assets/img/products/flora_and_fauna/trees/indian-summer-orange-beech/indian-summer-orange-beech-original.webp</original>
</imageURL>
<subCategory>Trees</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>17.99;20.85;29.90</price>
</product>
<product>
<name>Indian Summer Young Ashes</name>
<shortDescription>4 small Ashes on a parking lot.</shortDescription>
<longDescription>4 beautiful colored ashes standing in front of a green wood background, creating a nice contrast between the red ashes and the green trees in the back. Another fall themed poster for your home.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/trees/indian-summer-young-ashes/indian-summer-young-ashes-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/trees/indian-summer-young-ashes/indian-summer-young-ashes-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/trees/indian-summer-young-ashes/indian-summer-young-ashes-large.webp</large>
<original>/assets/img/products/flora_and_fauna/trees/indian-summer-young-ashes/indian-summer-young-ashes-original.webp</original>
</imageURL>
<subCategory>Trees</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>16.67;27.90;34.00</price>
</product>
<product>
<name>Indian Summer Young Birches</name>
<shortDescription>Small trees next to a prakingspace</shortDescription>
<longDescription>Birches are symbolizing renewal and purification, and we hope to project this through our poster into your room. Good to know: the birchbark is fantastic to create a fire, so if you are stuck in the cold or wet wildness, using birchbark will help.</longDescription>
<imageURL>
<small>/assets/img/products/flora_and_fauna/trees/indian-summer-young-birches/indian-summer-young-birches-small.webp</small>
<medium>/assets/img/products/flora_and_fauna/trees/indian-summer-young-birches/indian-summer-young-birches-medium.webp</medium>
<large>/assets/img/products/flora_and_fauna/trees/indian-summer-young-birches/indian-summer-young-birches-large.webp</large>
<original>/assets/img/products/flora_and_fauna/trees/indian-summer-young-birches/indian-summer-young-birches-original.webp</original>
</imageURL>
<subCategory>Trees</subCategory>
<availableSize>16x12;32x24;64x48</availableSize>
<price>16.98;29.99;45.50</price>